language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "sVtisbHVpKLizajT4RUHAQE3ZFIYfK24ruH1K7COi5t281Eqi6Yn/Mf/WH2c\nlr/3alvAea4s6oaRv3lw304VBSNYEPtbCs8f06tu1b6EJg3Fj6pp/SvTpOBy\nQFId8A+gqC4Uy0UsGsSthR2EpbNkCL3DcFRNkupbX+7m/2InT1g="
